### ISSUE TITLE
Not connecting to Windows devices

### ISSUE THREAD

**Issue by MrNyawka** [ginkage/wearmouse#16]
When I'm trying to connect to my phone, it's perfectly working, connects with 1-2 secs
Same effect when I'm connecting to TV, all good
But when I'm trying to connect to my Windows PC, it frozes with "Connecting..." status message
If I restart the app, it locks in the same way as described here: #9 
The strange thing is that at the first installation everything worked fine, but when I deleted the app and installed it again, I faced this issue
I did factory reset on my watch, it didn't help me
Tried on different Windows devices, so the problem isn't in bluetooth module

**Comment by ginkage** [comment]
Well, if anything, it does work for me on Windows without issues... What watch are you using?
Also, when you face connection issues, please try turning Airplane mode on the watch on and off, and re-pairing the watch with your computer (ideally, try restarting Bluetooth on the computer after unpairing). Don't forget that the app should be running (preferably not going into sleep) while pairing. Usually when you initiate the pairing from your computer it connects automatically. Let me know if any of this worked for you.

**Comment by MrNyawka** [comment]
Oooooh, thank you! I always tried to connect from watch to PC and when I typed PIN on watch, I needed to off the screen (go into sleep) of the watch and only then I receive notification about connection. Now I tried to connect from PC, and it's automatically connected as you described after I entered PIN on watch
Watch (if needed): TicWatch Pro 3 GPS
