### ISSUE TITLE
On Galaxy Watch 4 Classic, WearOS4 (OneUI 5)  4 when selecting the keyboard input in Wear Mouse just results in a black screen, so entering data or text while using the mouse is impossible

### ISSUE THREAD

**Issue by CEZARXV1** [ginkage/wearmouse#23]

**Comment by ismetertugral** [comment]
Change default keyboard to samsung keyboard. It works for me. Not supported GBoard

**Comment by ginkage** [comment]
You can also turn on the setting "stay connected in background", that should fix it as well.

**Comment by ginkage** [comment]
OK, scratch the above, it is a known issue with Wear 4 on Samsung, see here:
https://www.reddit.com/r/GalaxyWatch/comments/15v0f1d/gboard_doesnt_work_on_gw6_anyone_else/

**Comment by ginkage** [comment]
Closing as it's a GBoard issue, and there's nothing I can do about it.
