### ISSUE TITLE
Testing device support

### ISSUE THREAD

**Issue by profilku** [ginkage/wearmouse#3]
Hello, this is awesome app.
I am using TicWatch Pro Wear OS 2.3, it works well when downloading from Store.
But when i try to build this and push to my Device it said it is not supported (API 26 < API28) , when i try to lower the MinSDK it got missing "android.bluetooth.BluetoothHidDevice".
So the production version is different from this version ? 

Thanks a lot and regards

**Comment by ginkage** [comment]
Hi!
Thank you for the feedback. :)
The Play Store version is indeed slightly different. The API for emulating a Bluetooth Input Device has been introduced in SDK 26, but it was hidden at the time, and it was a bit different (even the class names were different, as were a few other things).
The code that is able to use both APIs is a lot more complex (with a couple additional unnecessary abstraction layers), calls hidden API (which itself is highly discouraged) via reflection-like mechanism (which is not guaranteed to always work). Releasing that code "as is" would basically defeat the whole purpose of making a sample code for the final and public API introduced in SDK 28.
But don't worry, your TicWatch Pro is most likely to receive a Pie update in a few weeks, so you'll be able to use this code without any problems!

**Comment by profilku** [comment]
Glad to hear that, definetely will wait to try this
Thank you for your clear explanation :)

**Comment by horstle** [comment]
Hi, I have a Ticwatch Pro, too. A few days ago I realised it was updated without me noticing (maybe during a reset I made), so I tried compiling the app myself and it works!
I guess this issue can be closed.

**Comment by profilku** [comment]
Wow thats great ! Thanks i think this issue is already solved !
