### ISSUE TITLE
Bug: Version 1.25 (Google Play) always crashes when selecting a paired device. Downgrading to 1.24 fixes issue.

### ISSUE THREAD

**Issue by Software27425** [ginkage/wearmouse#30]
1.25 on Google Play store seems unusable for me for whatever reason. It crashes when selecting my paired device. Crash still occurs on a fresh install and clearing data.

So I uninstalled it and then sideloaded the 1.24 universal APK from github using ADB. This time, selecting the paired device works and I can proceed to use the app.

Device: Samsung Galaxy Watch 7 (WearOS 5) and Motorola phone on Android 14.

**Comment by ginkage** [comment]
It would really help if you could collect a bugreport from your watch. I don't have a Watch 7 (I've only got Watch 4, and it works just fine), so "it crashes" is unfortunately as unhelpful as it gets. Sorry.

**Comment by Software27425** [comment]
My watch's developer options has a setting called "bug report writer" that I think compiles some kind of file after clicking a bug icon. Is that the way to do it after experiencing a crash?

**Comment by ginkage** [comment]
That might help, yes. :)

**Comment by ginkage** [comment]
This should now be fixed.
