### ISSUE TITLE
App crashing after selecting "Connect" 

### ISSUE THREAD

**Issue by harshmpanchal18** [ginkage/wearmouse#31]
Hey,

I'm using Samsung Galaxy watch 6 classic and trying to connect Google pixel 7 and my windows 10 laptop to WearMouse app, even after being connected, it shows disconnected, when I try to connect, the app crashes. Not sure what is the root cause!!

**Comment by ilyapro** [comment]
same trouble on samsung galaxy watch 7

**Comment by ginkage** [comment]
This is probably fixed now.
