### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by YoMamasNerd** [ginkage/wearmouse#5]
Is there any way to donate?
This App is great and I want to support the developer.

**Comment by ginkage** [comment]
Thank you for your kind words, but I'm afraid I'm legally not allowed to make any kind of profit on this app, including donations, if I understand T&C's correctly.
I'll try clarifying this though, maybe I'm actually wrong (I know for a fact that paid app, in-app purchases and ads are clearly off the table, but it's not clear if donations are indeed forbidden) and will reply as soon as I get the answer.
