### ISSUE TITLE
Is there any change to run this app on Android 8.0?

### ISSUE THREAD

**Issue by P-Kang-code** [ginkage/wearmouse#7]
Is there any change to run this app on Android 8.0, because my watch only support API 26. And i find this APP request some Class that only available on SDK 28. If i want to run this app on Android 8.0, which parts do I need to modify.
Thanks a lot and regards.

**Comment by P-Kang-code** [comment]
it's all because my watch is HUAWEI WATCH 2 and it don't have the access to the Google store. So i want to modify this code to make it suitable.

**Comment by horstle** [comment]
The Play Store version is a bit different (as explained in #3). Maybe you could download an APK of that version somewhere.

**Comment by ginkage** [comment]
Hi!
It was already mentioned in the issue #3 why the source code for Android 8.0 is not available.
As for Huawei Watch 2, you probably mean the Chinese version, which only has Huawei Store available. Unfortunately, I am unable to register as a developer for Huawei Store as it's only allowed to do in a handful of countries (feel free to complain to Huawei about it).
That said, the watch itself is of course fully supported, and you can download the APK [here](https://drive.google.com/file/d/1GMaFgwCxpMyvhrbskQFY1VaG0_IKDbEl/view?usp=sharing) — it's a slightly newer version than the one in the Play Store, which includes pull request #6 .
Please let me know if it works for you.

**Comment by P-Kang-code** [comment]
yes, it works pretty well. Thank you so much.
