### ISSUE TITLE
Connecting to Bluetooth devices fails after exiting app while connecting

### ISSUE THREAD

**Issue by fmeum** [ginkage/wearmouse#9]
Connecting to Bluetooth devices is no longer possible (on API level 27) after the following steps:

1. Launch WearMouse and selects a device
2. Tap on "Connect"
3. Exit the app by swiping right while the status of the device is shown as "Connecting..."

After these steps, device entries no longer react to touches and connecting to devices is thus no longer possible. This is not fixed by force stopping the app, but is fixed by turning Bluetooth off and on again in the watch settings.

**Comment by ginkage** [comment]
And this is just one of the reasons why this API wasn't public until SDK 28. :)

**Comment by fmeum** [comment]
Luckily this bug is not triggered too easily and the obvious workaround does fix it. Thanks for the confirmation that the issue is indeed unfixable on API levels <= 27.
